export const RECEIVE_QUESTIONS = 'RECEIVE_QUESTIONS'
export const SAVE_QUESTION_ANSWER = 'SAVE_QUESTION_ANSWER'
export const ADD_NEW_QUESTION = 'ADD_NEW_QUESTION'
export const SELECT_QUESTION = 'SELECT_QUESTION'

export const SET_AUTHED_USER = 'SET_AUTHED_USER'

export const RECEIVE_USERS = 'RECEIVE_USERS'
export const ADD_USER_QUESTION = 'ADD_USER_QUESTION'
export const USER_ANSWER_QUESTION = 'USER_ANSWER_QUESTION'